labels:
  platform: linux/amd64
when:
  event: [push, pull_request, tag]
steps:
  - name: build
    image: repo.osgeo.org/postgis/build-test:trisquel3
    when:
      - event: push
        path: 
          include: ['doc/*', '.woodpecker/*.yaml']
    commands:
      - export PATH=/usr/lib/postgresql/13/bin:$PATH
      - ./autogen.sh
      - mkdir -p build-docs && cd build-docs
      - ../configure
      - make docs
      - make -C doc check
      - make docs-localized
      - make -C doc/ check-localized
